title: HTD(a)A
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

url: https://zainkarsan7.github.io/htdaa

aux_links:
  Template Repository: https://zainkarsan7.github.io/htdaa
